apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch-master
    release: elasticsearch
  name: elasticsearch-master
spec:
  clusterIP: 
  ports:
  - name: http
    port: 9200
  - name: transport
    port: 9300
  selector:
    app: elasticsearch-master
    release: elasticsearch

